modLoader="javafml"
loaderVersion="[29,)"

#issueTrackerURL="http://my.issue.tracker/"
[[mods]]
modId="keepfov"
version="${file.jarVersion}"
displayName="Keep FOV"
#updateJSONURL="http://myurl.me/"
#displayURL="http://example.com/"

#logoFile="examplemod.png"

authors="Naxanria"
description='''
Keeps your fov the same
'''

[[dependencies.keepfov]]
    modId="forge"
    mandatory=true
    versionRange="[30.0.0,)"
    ordering="NONE"
    side="CLIENT"

[[dependencies.keepfov]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.15.1,)"
    ordering="NONE"
    side="BOTH"
